-- CRIAÇÃO DAS TABELAS

CREATE TABLE TAB_CLIENTE(
    ID_CLIENTE SERIAL PRIMARY KEY NOT NULL,
    NOME_CLIENTE VARCHAR(50),
    CPF_CLIENTE VARCHAR(11) UNIQUE CHECK(LENGTH(CPF_CLIENTE) = 11),
    DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE TAB_SERVICOS(
    ID_SERV INTEGER PRIMARY KEY,
    TIPO_SERV VARCHAR(50),
    PRECO_SERVICO NUMERIC(10,2)
);

CREATE TABLE TAB_FUNCIONARIO(
    ID_FUNC SERIAL PRIMARY  KEY NOT NULL,
    NOME_FUNC VARCHAR(50) NOT NULL,
    MATRICULA VARCHAR(7) NOT NULL UNIQUE  CHECK(LENGTH(MATRICULA) = 7),
    DATA_NASCIMENTO DATE NOT NULL 
);

CREATE TABLE PRD_ATENDIMENTO(
    ID_ATEND SERIAL PRIMARY KEY NOT NULL,
    STATUS_ATEND VARCHAR(50) DEFAULT "ABERTO",
    VALIDADE_ATEND TIMESTAMP WITH TIME ZONE CURRENT_TIMESTAMP,
    MOTIVO_ATEND TEXT,
    FEEDBACK SERIAL NOT NULL CHECK(FEEDBACK >=0),
    PROTOCOLO VARCHAR(15) DEFAULT "XXXXX.000.000-0", -- O TEMPLATE SERÁ UM SUFIXO DO TIPO DE SERVIÇO NO PROTOCOLO
    TEMPO_ATEND INT NOT NULL CHECK (TEMPO_ATEND >= 0),
    ID_FK_CLIENTE INT NOT NULL,
    ID_FK_FUNC INT NOT NULL,
    CONSTRAINT FK_CLIENTE FOREIGN KEY(ID_FK_CLIENTE) REFERENCES TAB_CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_FUNC FOREIGN KEY(ID_FK_FUNC) REFERENCES TAB_FUNCIONARIO(ID_FUNC)
  );

CREATE TABLE TAB_ITENS_SERV(
    ID_ITENS_SERV SERIAL PRIMARY,
    VALIDACAO VARCHAR(50),
    CONFERENCIA VARCHAR(50),
    BIOMETRIA_DIGITAL VARCHAR(50) 
);

CREATE TABLE AUX_SERV_ATEND(
    ID_FK_SERV INT NOT NULL,
    CONSTRAINT FK_AUX_SERV FOREIGN KEY(ID_FK_SERV) REFERENCES TAB_SERVICOS(ID_SERV)
    ID_FK_ATEND INT NOT NULL,
    CONSTRAINT FK_AUX_ATEND FOREIGN KEY(ID_FK_ATEND) REFERENCES PRD_ATENDIMENTO(ID_ATEND)
);

CREATE TABLE AUX_SERV_ITEM(
    ID_FK_SERV INT NOT NULL,
    CONSTRAINT FK_SERV FOREIGN KEY(ID_FK_SERV) REFERENCES TAB_SERVICOS(ID_SERV)
    ID_FK_ITEM_SERV INT NOT NULL,
    CONSTRAINT FK_ITEM_SERV FOREIGN KEY(ID_FK_ITEM_SERV) REFERENCES TAB_ITENS_SERV(ID_ITENS_SERV)
);


--VALIDAÇÃO DE REGRAS

--TESTE DE CLIENTES
INSERT INTO PRD_SAC.TAB_CLIENTE(NOME_CLIENTE, CPF_CLIENTE)
VALUES("ALESSANDRO NUNES", "07456935556")
ON CONFLICT(CPF_CLIENTE)
DO NOTHING;


--TESTE DE FUNCIONARIOS
INSERT INTO PRD_SAC.TAB_FUNCIONARIO(NOME_FUNC, MATRICULA, DATA_NASCIMENTO)
VALUES("KIARA SILVA", "B62379", "08-06-2005")
ON CONFLICT(ID_FUNC)
DO UPDATE SET 
NOME_FUNC = EXCLUDE.NOME_FUNC
MATRICULA = EXCLUDE.MATRICULA
DATA_NASCIMENTO = EXCLUDE.DATA_NASCIMENTO;

--TESTE DE SERVIÇOS
INSERT INTO PRD_SAC.TAB_SERVICOS (TIPO_SERV, PRECO_SERVICO)
VALUES("VALIDAÇÃO", 0.0);

INSERT INTO PRD_SAC.TAB_ITENS_SERV(VALIDACAO)
VALUES("Verificação de horário agendado");

INSERT INTO PRD_SAC.TAB_ITENS_SERV(VALIDACAO)
VALUES("Código de Acesso a Videoconferência");

INSERT INTO PRD_SAC.TAB_ITENS_SERV(VALIDACAO)
VALUES("Liberação de Agência");

INSERT INTO PRD_SAC.TAB_ITENS_SERV(VALIDACAO)
VALUES("Liberação de Agência Bancária Parceira habilitada no Smartphone do cliente"); --Erro forçado para limites de caractéres

INSERT INTO PRD_SAC.AUX_ITEM_SERV(ID_FK_SERV, ID_FK_ITEM_SERV)
VALUES(1, 2);


--TESTE DE ATENDIMENTO
INSERT INTO PRD_SAC.PRD_ATENDIMENTO(
    STATUS_ATEND,
    VALDIADE_ATEND,
    MOTIVO_ATEND,
    FEEDBACK,
    PROTOCOLO,
    TEMPO_ATEND
    ID_FK_CLIENTE,
    ID_FK_FUNC
)
VALUES(
    "EM ATENDIMENTO",
    "1788676800"
    "fiz o agendamento da videoconferencia mas n recebi o codigo de acesso"
    5
    "VALID.123.321.3",
    13,
    1,
    2
)
-- CONFLITO DE ID FUNCIONARIO


--TESTE DE ATENDIMENTO
INSERT INTO PRD_SAC.PRD_ATENDIMENTO(
    STATUS_ATEND,
    VALDIADE_ATEND,
    MOTIVO_ATEND,
    FEEDBACK,
    PROTOCOLO,
    TEMPO_ATEND
    ID_FK_CLIENTE,
    ID_FK_FUNC
)
VALUES(
    "CANCELADO",
    "1788676800"
    "fiz o agendamento e n me chamaram"
    0
    "VALID.123.321.3",
    0,
    1,
    1
)
ON CONFLICT(PROTOCOLO) -- ONDE HOUVER CONFLITO DE PROTOCOLO
WHERE STATUS_ATEND != 'CANCELADO' -- QUANDO FOR DIFERENTE DE CANCELADO
DO NOTHING; -- FAÇA NADA
--CONFLITO DE STATUS

--TESTE DE ATENDIMENTO
INSERT INTO PRD_SAC.PRD_ATENDIMENTO(
    STATUS_ATEND,
    VALDIADE_ATEND,
    MOTIVO_ATEND,
    FEEDBACK,
    PROTOCOLO,
    TEMPO_ATEND
    ID_FK_CLIENTE,
    ID_FK_FUNC
)
VALUES(
    "CANCELADO",
    "1788676800"
    "fiz o agendamento e n me chamaram"
    -1
    "VALID.123.321.3",
    0,
    1,
    1
)
WHERE STATUS_ATEND != 'CANCELADO'
-- CONFLITO DE FEEDBACK

INSERT INTO PRD_SAC.PRD_ATENDIMENTO(
    STATUS_ATEND,
    VALDIADE_ATEND,
    MOTIVO_ATEND,
    FEEDBACK,
    PROTOCOLO,
    TEMPO_ATEND
    ID_FK_CLIENTE,
    ID_FK_FUNC
)
VALUES(
    "EM ATENDIMENTO",
    "1788676800"
    "Sucesso!"
    5
    "VALID.133.321.3",
    4,
    1,
    1
)
WHERE STATUS_ATEND != 'CANCELADO'

INSERT INYO PRD_SAC.AUX_SERV_ATEND(ID_FK_SERV, ID_FK_ITEM)
VALUES(1, 2)